# Generated by Django 4.2.6 on 2023-10-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.BigIntegerField()),
                ('occ', models.CharField(max_length=40)),
                ('addr', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('dur', models.IntegerField()),
                ('tech', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
